# Generated by Django 5.1 on 2025-01-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdata',
            name='angleValue',
            field=models.FloatField(default=False),
        ),
    ]
