# Generated by Django 5.1 on 2025-01-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_backupsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='angle_stored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comp_sr_no', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=10)),
                ('parameter_name', models.CharField(max_length=100)),
                ('nominal', models.FloatField()),
                ('output', models.FloatField()),
                ('angleValue', models.FloatField(default=False)),
                ('andjacentValue', models.FloatField()),
                ('channelValue', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='MeasurementData',
        ),
    ]
